import Quality from "./Quality.js";

const Product = {
  ALINOR_AMPHORA_DELICATE: "alinor amphora, delicate",
  ARGONIAN_TOTEM_OF_SKULLS: "argonian totem of skulls",
  ASHLANDER_PLATTER_CERAMIC: "ashlander platter, ceramic",
  BRETON_AMPHORA_CERAMIC: "breton amphora, ceramic",
  BRETON_DESK: "breton desk",
  BRETON_NIGHTSTAND_OPEN: "breton nightstand, open",
  BRETON_SCONCE_TORCH: "breton sconce, torch",
  COMMON_CANDLE_LASTING: "common candle, lasting",
  COMMON_CANDLE_SET: "common candle, set",
  DARK_ELF_CANDLE_CLAW_BASE: "dark elf candle, claw base",
  DARK_ELF_CAULDRON_BANDED: "dark elf cauldron, banded",
  DARK_ELF_LANTERN_OIL: "dark elf lantern, oil",
  DRES_BOWL_EMPTY: "dres bowl, empty",
  DRES_CANDLES_MEDITATION: "dres candles, meditation",
  DRES_LANTERN_STATIONARY: "dres lantern, stationary",
  HAGRAVEN_CAULDRON_RITUAL: "hagraven cauldron, ritual",
  INDORIL_STREETLIGHT_FULL_STONE: "indoril streetlight, full stone",
  INDORIL_STREETLIGHT_STONE: "indoril streetlight, stone",
  KHAJIIT_CARPET_CRESCENT_MOONS: "khajiit carpet, crescent moons",
  LAVA_FOOT_SOUP_AND_SALTRICE: "lava foot soup-and-saltrice",
  NORD_CANDLEHOLDER_CUP: "nord candleholder, cup",
  ORCISH_BANNER_WORN: "orcish banner, worn",
  ORCISH_BRAZIER_SMOLDERING: "orcish brazier, smoldering",
  ORCISH_CHANDELIER_PRACTICAL: "orcish chandelier, practical",
  ORCISH_LANTERN_HOODED: "orcish lantern, hooded",
  ORCISH_VESSEL_SEALED_CERAMIC: "orcish vessel, sealed ceramic",
  REDGUARD_BAR_LONG_CABINET: "redguard bar, long cabinet",
  REDGUARD_BENCH_SLATTED: "redguard bench, slatted",
  REDGUARD_BOOKCASE_FULL: "redguard bookcase, full",
  REDGUARD_CANDLESTICK_PRACTICAL: "redguard candlestick, practical",
  REDGUARD_CURTAIN_SMOKY: "redguard curtain, smoky",
  REDGUARD_MAT_SUNSET: "redguard mat, sunset",
  REDGUARD_POT_CAPPED: "redguard pot, capped",
  REDGUARD_POT_SEALED: "redguard pot, sealed",
  REDGUARD_STREETLAMP_SINGLE: "redguard streetlamp, single",
  REDGUARD_WAGON_MERCHANT: "redguard wagon, merchant",
  REDORAN_SPOON_WOODEN: "redoran spoon, wooden",
  WITCHMOTHERS_POTENT_BREW: "witchmother's potent brew",
  WOOD_ELF_BAR_SHORT: "wood elf bar, short",
  WOOD_ELF_BONE_CHIMES: "wood elf bone chimes",
  WOOD_ELF_DIVIDER_RELAXED: "wood elf divider, relaxed",
  WOOD_ELF_PITCHER_PAINTED: "wood elf pitcher, painted",
};

Product.properties = {
  "alinor amphora, delicate": {
    name: "Alinor Amphora, Delicate",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/high-elf-amphora-delicate/",
    key: "alinor amphora, delicate",
  },
  "argonian totem of skulls": {
    name: "Argonian Totem of Skulls",
    qualityKey: Quality.EPIC,
    url: "https://eso.mmo-fashion.com/argonian-totem-of-skulls/",
    key: "argonian totem of skulls",
  },
  "ashlander platter, ceramic": {
    name: "Ashlander Platter, Ceramic",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/ashlander-platter-ceramic/",
    key: "ashlander platter, ceramic",
  },
  "breton amphora, ceramic": {
    name: "Breton Amphora, Ceramic",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/breton-amphora-ceramic/",
    key: "breton amphora, ceramic",
  },
  "breton desk": {
    name: "Breton Desk",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/breton-desk/",
    key: "breton desk",
  },
  "breton nightstand, open": {
    name: "Breton Nightstand, Open",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/breton-nightstand-open/",
    key: "breton nightstand, open",
  },
  "breton sconce, torch": {
    name: "Breton Sconce, Torch",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/breton-sconce-torch/",
    key: "breton sconce, torch",
  },
  "common candle, lasting": {
    name: "Common Candle, Lasting",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/common-candle-lasting/",
    key: "common candle, lasting",
  },
  "common candle, set": {
    name: "Common Candle, Set",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/common-candle-set/",
    key: "common candle, set",
  },
  "dark elf candle, claw base": {
    name: "Dark Elf Candle, Claw Base",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/dark-elf-candle-claw-base/",
    key: "dark elf candle, claw base",
  },
  "dark elf cauldron, banded": {
    name: "Dark Elf Cauldron, Banded",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/dark-elf-cauldron-banded/",
    key: "dark elf cauldron, banded",
  },
  "dark elf lantern, oil": {
    name: "Dark Elf Lantern, Oil",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/dark-elf-lantern-oil/",
    key: "dark elf lantern, oil",
  },
  "dres bowl, empty": {
    name: "Dres Bowl, Empty",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/dres-bowl-empty/",
    key: "dres bowl, empty",
  },
  "dres candles, meditation": {
    name: "Dres Candles, Meditation",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/dres-candles-meditation/",
    key: "dres candles, meditation",
  },
  "dres lantern, stationary": {
    name: "Dres Lantern, Stationary",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/dres-lantern-stationary/",
    key: "dres lantern, stationary",
  },
  "hagraven cauldron, ritual": {
    name: "Hagraven Cauldron, Ritual",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/hagraven-cauldron-ritual/",
    key: "hagraven cauldron, ritual",
  },
  "indoril streetlight, full stone": {
    name: "Indoril Streetlight, Full Stone",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/indoril-streetlight-full-stone/",
    key: "indoril streetlight, full stone",
  },
  "indoril streetlight, stone": {
    name: "Indoril Streetlight, Stone",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/indoril-streetlight-stone/",
    key: "indoril streetlight, stone",
  },
  "khajiit carpet, crescent moons": {
    name: "Khajiit Carpet, Crescent Moons",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/khajiit-carpet-crescent-moons/",
    key: "khajiit carpet, crescent moons",
  },
  "lava foot soup-and-saltrice": {
    name: "Lava Foot Soup-and-Saltrice",
    qualityKey: Quality.SUPERIOR,
    key: "lava foot soup-and-saltrice",
  },
  "nord candleholder, cup": {
    name: "Nord Candleholder, Cup",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/nord-candleholder-cup/",
    key: "nord candleholder, cup",
  },
  "orcish banner, worn": {
    name: "Orcish Banner, Worn",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/orcish-banner-worn/",
    key: "orcish banner, worn",
  },
  "orcish brazier, smoldering": {
    name: "Orcish Brazier, Smoldering",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/orcish-brazier-smoldering/",
    key: "orcish brazier, smoldering",
  },
  "orcish chandelier, practical": {
    name: "Orcish Chandelier, Practical",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/orcish-chandelier-practical/",
    key: "orcish chandelier, practical",
  },
  "orcish lantern, hooded": {
    name: "Orcish Lantern, Hooded",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/orcish-lantern-hooded/",
    key: "orcish lantern, hooded",
  },
  "orcish vessel, sealed ceramic": {
    name: "Orcish Vessel, Sealed Ceramic",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/orcish-vessel-sealed-ceramic/",
    key: "orcish vessel, sealed ceramic",
  },
  "redguard bar, long cabinet": {
    name: "Redguard Bar, Long Cabinet",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-cabinet-bar/",
    key: "redguard bar, long cabinet",
  },
  "redguard bench, slatted": {
    name: "Redguard Bench, Slatted",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-bench-slatted/",
    key: "redguard bench, slatted",
  },
  "redguard bookcase, full": {
    name: "Redguard Bookcase, Full",
    qualityKey: Quality.EPIC,
    url: "https://eso.mmo-fashion.com/redguard-bookcase-full/",
    key: "redguard bookcase, full",
  },
  "redguard candlestick, practical": {
    name: "Redguard Candlestick, Practical",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-candlestick-practical/",
    key: "redguard candlestick, practical",
  },
  "redguard curtain, smoky": {
    name: "Redguard Curtain, Smoky",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-curtain-smoky/",
    key: "redguard curtain, smoky",
  },
  "redguard mat, sunset": {
    name: "Redguard Mat, Sunset",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/redguard-mat-sunset/",
    key: "redguard mat, sunset",
  },
  "redguard pot, capped": {
    name: "Redguard Pot, Capped",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-pot-capped/",
    key: "redguard pot, capped",
  },
  "redguard pot, sealed": {
    name: "Redguard Pot, Sealed",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-pot-sealed/",
    key: "redguard pot, sealed",
  },
  "redguard streetlamp, single": {
    name: "Redguard Streetlamp, Single",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-streetlamp-single/",
    key: "redguard streetlamp, single",
  },
  "redguard wagon, merchant": {
    name: "Redguard Wagon, Merchant",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/redguard-wagon-merchant/",
    key: "redguard wagon, merchant",
  },
  "redoran spoon, wooden": {
    name: "Redoran Spoon, Wooden",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/redoran-spoon-wooden/",
    key: "redoran spoon, wooden",
  },
  "witchmother's potent brew": {
    name: "Witchmother's Potent Brew",
    qualityKey: Quality.EPIC,
    key: "witchmother's potent brew",
  },
  "wood elf bar, short": {
    name: "Wood Elf Bar, Short",
    qualityKey: Quality.FINE,
    url: "https://eso.mmo-fashion.com/wood-elf-bar-short/",
    key: "wood elf bar, short",
  },
  "wood elf bone chimes": {
    name: "Wood Elf Bone Chimes",
    qualityKey: Quality.EPIC,
    url: "https://eso.mmo-fashion.com/wood-elf-bone-chimes/",
    key: "wood elf bone chimes",
  },
  "wood elf divider, relaxed": {
    name: "Wood Elf Divider, Relaxed",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/wood-elf-divider-relaxed/",
    key: "wood elf divider, relaxed",
  },
  "wood elf pitcher, painted": {
    name: "Wood Elf Pitcher, Painted",
    qualityKey: Quality.SUPERIOR,
    url: "https://eso.mmo-fashion.com/wood-elf-pitcher-painted/",
    key: "wood elf pitcher, painted",
  },
};

Product.keys = () => Object.keys(Product.properties);

Product.values = () => Object.values(Product.properties);

Object.freeze(Product);

export default Product;
