import Category from "./Category.js";
import Character from "./Character.js";
import Craft from "./Craft.js";
import Ingredient from "./Ingredient.js";
import Product from "./Product.js";
import Quality from "./Quality.js";
import Resource from "./Resource.js";

const productIngredient = (productKey, amount) =>
  Ingredient.create({ productKey, amount });
const resourceIngredient = (resourceKey, amount) =>
  Ingredient.create({ resourceKey, amount });

const Recipe = {
  BLUEPRINT_BRETON_DESK: "blueprint: breton desk",
  BLUEPRINT_BRETON_NIGHTSTAND_OPEN: "blueprint: breton nightstand, open",
  BLUEPRINT_REDGUARD_BAR_LONG_CABINET: "blueprint: redguard bar, long cabinet",
  BLUEPRINT_REDGUARD_BENCH_SLATTED: "blueprint: redguard bench, slatted",
  BLUEPRINT_REDGUARD_BOOKCASE_FULL: "blueprint: redguard bookcase, full",
  BLUEPRINT_REDGUARD_BOOKCASE_PILED: "blueprint: redguard bookcase, piled",
  BLUEPRINT_REDGUARD_CANDLESTICK_PRACTICAL:
    "blueprint: redguard candlestick, practical",
  BLUEPRINT_REDGUARD_WAGON_MERCHANT: "blueprint: redguard wagon, merchant",
  BLUEPRINT_REDORAN_SPOON_WOODEN: "blueprint: redoran spoon, wooden",
  BLUEPRINT_WOOD_ELF_BAR_SHORT: "blueprint: wood elf bar, short",

  DESIGN_ALINOR_AMPHORA_DELICATE: "design: alinor amphora, delicate",
  DESIGN_ARGONIAN_TOTEM_OF_SKULLS: "design: argonian totem of skulls",
  DESIGN_ASHLANDER_PLATTER_CERAMIC: "design: ashlander platter, ceramic",
  DESIGN_COMMON_CANDLE_LASTING: "design: common candle, lasting",
  DESIGN_COMMON_CANDLE_SET: "design: common candle, set",
  DESIGN_DRES_BOWL_EMPTY: "design: dres bowl, empty",
  DESIGN_DRES_CANDLES_MEDITATION: "design: dres candles, meditation",
  DESIGN_ORCHISH_VESSEL_SEALED_CERAMIC: "design: orcish vessel, sealed ceramic",
  DESIGN_REDGUARD_POT_CAPPED: "design: redguard pot, capped",
  DESIGN_REDGUARD_POT_SEALED: "design: redguard pot, sealed",
  DESIGN_WOOD_ELF_BONE_CHIMES: "design: wood elf bone chimes",
  DESIGN_WOOD_ELF_PITCHER_PAINTED: "design: wood elf pitcher, painted",

  DIAGRAM_BRETON_SCONCE_TORCH: "diagram: breton sconce, torch",
  DIAGRAM_DARK_ELF_CANDLE_CLAW_BASE: "diagram: dark elf candle, claw base",
  DIAGRAM_DARK_ELF_CAULDRON_BANDED: "diagram: dark elf cauldron, banded",
  DIAGRAM_NORD_CANDLEHOLDER_CUP: "diagram: nord candleholder, cup",
  DIAGRAM_ORCISH_CHANDELIER_PRACTICAL: "diagram: orcish chandelier, practical",
  DIAGRAM_ORCISH_LANTERN_HOODED: "diagram: orcish lantern, hooded",
  DIAGRAM_REDGUARD_STREETLAMP_SINGLE: "diagram: redguard streetlamp, single",

  FORMULA_DARK_ELF_LANTERN_OIL: "formula: dark elf lantern, oil",
  FORMULA_DRES_LANTERN_STATIONARY: "formula: dres lantern, stationary",
  FORMULA_INDORIL_STREETLIGHT_FULL_STONE:
    "formula: indoril streetlight, full stone",
  FORMULA_INDORIL_STREETLIGHT_STONE: "formula: indoril streetlight, stone",

  PATTERN_KHAJIIT_CARPET_CRESCENT_MOONS:
    "pattern: khajiit carpet, crescent moons",
  PATTERN_ORCISH_BANNER_WORN: "pattern: orcish banner, worn",
  PATTERN_REDGUARD_ARMCHAIR_CUSHIONED: "pattern: redguard armchair, cushioned",
  PATTERN_REDGUARD_ARMCHAIR_STARRY: "pattern: redguard armchair, starry",
  PATTERN_REDGUARD_BENCH_PADDED: "pattern: redguard bench, padded",
  PATTERN_REDGUARD_CARPET_DUNES: "pattern: redguard carpet, dunes",
  PATTERN_REDGUARD_CURTAIN_SMOKY: "pattern: redguard curtain, smoky",
  PATTERN_REDGUARD_MAT_SUNSET: "pattern: redguard mat, sunset",
  PATTERN_REDGUARD_RUNNER_SUN: "pattern: redguard runner, sun",
  PATTERN_WOOD_ELF_DIVIDER_RELAXED: "pattern: wood elf divider, relaxed",

  PRAXIS_BRETON_AMPHORA_CERAMIC: "praxis: breton amphora, ceramic",
  PRAXIS_HAGRAVEN_CAULDRON_RITUAL: "praxis: hagraven cauldron, ritual",
  PRAXIS_ORCISH_BRAZIER_SMOLDERING: "praxis: orcish brazier, smoldering",

  RECIPE_LAVA_FOOT_SOUP_AND_SALTRICE: "recipe: lava foot soup-and-saltrice",
  RECIPE_WITCHMOTHERS_POTENT_BREW: "recipe: witchmother's potent brew",
};

Recipe.properties = {
  // ///////////////////////////////////////////////////////////////////////////
  // Blueprint
  "blueprint: breton desk": {
    name: "Blueprint: Breton Desk",
    categoryKey: Category.LIBRARY,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 7),
      resourceIngredient(Resource.MOLYBDENUM, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.BRETON_DESK),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/breton-desk",
    key: "blueprint: breton desk",
  },
  "blueprint: breton nightstand, open": {
    name: "Blueprint: Breton Nightstand, Open",
    categoryKey: Category.SUITE,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 6),
      resourceIngredient(Resource.MOLYBDENUM, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.BRETON_NIGHTSTAND_OPEN),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/breton-nightstand-open",
    key: "blueprint: breton nightstand, open",
  },
  "blueprint: redguard bar, long cabinet": {
    name: "Blueprint: Redguard Bar, Long Cabinet",
    categoryKey: Category.DINING,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 6),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.REDGUARD_BAR_LONG_CABINET),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-bar-long-cabinet",
    key: "blueprint: redguard bar, long cabinet",
  },
  "blueprint: redguard bench, slatted": {
    name: "Blueprint: Redguard Bench, Slatted",
    categoryKey: Category.DINING,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 5),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.REDGUARD_BENCH_SLATTED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-bench-slatted",
    key: "blueprint: redguard bench, slatted",
  },
  "blueprint: redguard bookcase, full": {
    name: "Blueprint: Redguard Bookcase, Full",
    categoryKey: Category.LIBRARY,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 13),
      resourceIngredient(Resource.MUNDANE_RUNE, 9),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 8),
      resourceIngredient(Resource.STARMETAL, 15),
      resourceIngredient(Resource.MASTIC, 3),
    ],
    output: productIngredient(Product.REDGUARD_BOOKCASE_FULL),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.EPIC,
    url: "https://eso-housing.com/furniture/redguard-bookcase-full",
    key: "blueprint: redguard bookcase, full",
  },
  "blueprint: redguard bookcase, piled": {
    name: "Blueprint: Redguard Bookcase, Piled",
    categoryKey: Category.LIBRARY,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 12),
      resourceIngredient(Resource.MUNDANE_RUNE, 8),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 8),
      resourceIngredient(Resource.STARMETAL, 15),
      resourceIngredient(Resource.MASTIC, 3),
    ],
    output: productIngredient(Product.REDGUARD_BOOKCASE_PILED),
    qualityKey: Quality.EPIC,
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=13664&ItemNamePattern=Blueprint%3A+Redguard+Bookcase%2C+Piled&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-bookcase-piled",
    key: "blueprint: redguard bookcase, piled",
  },
  "blueprint: redguard candlestick, practical": {
    name: "Blueprint: Redguard Candlestick, Practical",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 4),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.REDGUARD_CANDLESTICK_PRACTICAL),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-candlestick-practical",
    key: "blueprint: redguard candlestick, practical",
  },
  "blueprint: redguard wagon, merchant": {
    name: "Blueprint: Redguard Wagon, Merchant",
    categoryKey: Category.COURTYARD,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 6),
      resourceIngredient(Resource.REGULUS, 4),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.REDGUARD_WAGON_MERCHANT),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-wagon-merchant",
    key: "blueprint: redguard wagon, merchant",
  },
  "blueprint: redoran spoon, wooden": {
    name: "Blueprint: Redoran Spoon, Wooden",
    categoryKey: Category.HEARTH,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 8),
      resourceIngredient(Resource.DECORATIVE_WAX, 5),
      resourceIngredient(Resource.OBSIDIAN, 10),
      resourceIngredient(Resource.TURPEN, 6),
    ],
    output: productIngredient(Product.REDORAN_SPOON_WOODEN),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/redoran-spoon-wooden",
    key: "blueprint: redoran spoon, wooden",
  },
  "blueprint: wood elf bar, short": {
    name: "Blueprint: Wood Elf Bar, Short",
    categoryKey: Category.HEARTH,
    craftKey: Craft.WOODWORKING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 5),
      resourceIngredient(Resource.BONE, 5),
      resourceIngredient(Resource.PITCH, 9),
    ],
    output: productIngredient(Product.WOOD_ELF_BAR_SHORT),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/wood-elf-bar-short",
    key: "blueprint: wood elf bar, short",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Design
  "design: alinor amphora, delicate": {
    name: "Design: Alinor Amphora, Delicate",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 5),
      resourceIngredient(Resource.MUNDANE_RUNE, 5),
      resourceIngredient(Resource.OCHRE, 4),
      resourceIngredient(Resource.CULANDA_LACQUER, 1),
      resourceIngredient(Resource.FLOUR, 20),
    ],
    qualityKey: Quality.FINE,
    output: productIngredient(Product.ALINOR_AMPHORA_DELICATE),
    ownerKey: Character.FRAK_LOCK,
    url: "https://eso-housing.com/furniture/alinor-amphora-delicate",
    key: "design: alinor amphora, delicate",
  },
  "design: argonian totem of skulls": {
    name: "Design: Argonian Totem of Skulls",
    categoryKey: Category.UNDERCROFT,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 10),
      resourceIngredient(Resource.MUNDANE_RUNE, 7),
      resourceIngredient(Resource.HEARTWOOD, 7),
      resourceIngredient(Resource.FLINT, 15),
      resourceIngredient(Resource.FROST_MIRRIAM, 3),
    ],
    output: productIngredient(Product.ARGONIAN_TOTEM_OF_SKULLS),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.EPIC,
    url: "https://eso-housing.com/furniture/argonian-totem-of-skulls",
    key: "design: argonian totem of skulls",
  },
  "design: ashlander platter, ceramic": {
    name: "Design: Ashlander Platter, Ceramic",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.HEARTWOOD, 4),
      resourceIngredient(Resource.MUNDANE_RUNE, 5),
      resourceIngredient(Resource.DECORATIVE_WAX, 9),
      resourceIngredient(Resource.ASH_CANVAS, 1),
      resourceIngredient(Resource.BERVEZ_JUICE, 3),
    ],
    output: productIngredient(Product.ASHLANDER_PLATTER_CERAMIC),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/ashlander-platter-ceramic",
    key: "design: ashlander platter, ceramic",
  },
  "design: common candle, lasting": {
    name: "Design: Common Candle, Lasting",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 3),
      resourceIngredient(Resource.NICKEL, 5),
      resourceIngredient(Resource.RAKEIPA, 2),
      resourceIngredient(Resource.MUNDANE_RUNE, 2),
      resourceIngredient(Resource.FLOUR, 20),
    ],
    output: productIngredient(Product.COMMON_CANDLE_LASTING),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/common-candle-lasting",
    key: "design: common candle, lasting",
  },
  "design: common candle, set": {
    name: "Design: Common Candle, Set",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 4),
      resourceIngredient(Resource.NICKEL, 5),
      resourceIngredient(Resource.FLOUR, 20),
    ],
    output: productIngredient(Product.COMMON_CANDLE_SET),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/common-candle-set",
    key: "design: common candle, set",
  },
  "design: dres bowl, empty": {
    name: "Design: Dres Bowl, Empty",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 7),
      resourceIngredient(Resource.HEARTWOOD, 5),
      resourceIngredient(Resource.OBSIDIAN, 8),
      resourceIngredient(Resource.BERVEZ_JUICE, 3),
    ],
    output: productIngredient(Product.DRES_BOWL_EMPTY),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/dres-bowl-empty",
    key: "design: dres bowl, empty",
  },
  "design: dres candles, meditation": {
    name: "Design: Dres Candles, Meditation",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 7),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 5),
      resourceIngredient(Resource.OBSIDIAN, 8),
      resourceIngredient(Resource.BERVEZ_JUICE, 3),
    ],
    output: productIngredient(Product.DRES_CANDLES_MEDITATION),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/dres-candles-meditation",
    key: "design: dres candles, meditation",
  },
  "design: orcish vessel, sealed ceramic": {
    name: "Design: Orcish Vessel, Sealed Ceramic",
    categoryKey: Category.UNDERCROFT,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 6),
      resourceIngredient(Resource.MANGANESE, 10),
      resourceIngredient(Resource.BERVEZ_JUICE, 3),
    ],
    output: productIngredient(Product.ORCISH_VESSEL_SEALED_CERAMIC),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/orcish-vessel-sealed-ceramic",
    key: "design: orcish vessel, sealed ceramic",
  },
  "design: redguard pot, capped": {
    name: "Design: Redguard Pot, Capped",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 5),
      resourceIngredient(Resource.REGULUS, 3),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.FLOUR, 20),
    ],
    output: productIngredient(Product.REDGUARD_POT_CAPPED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-pot-capped",
    key: "design: redguard pot, capped",
  },
  "design: redguard pot, sealed": {
    name: "Design: Redguard Pot, Sealed",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 5),
      resourceIngredient(Resource.REGULUS, 3),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.FLOUR, 20),
    ],
    output: productIngredient(Product.REDGUARD_POT_SEALED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-pot-sealed",
    key: "design: redguard pot, sealed",
  },
  "design: wood elf bone chimes": {
    name: "Design: Wood Elf Bone Chimes",
    categoryKey: Category.UNDERCROFT,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 9),
      resourceIngredient(Resource.CLEAN_PELT, 7),
      resourceIngredient(Resource.HEARTWOOD, 6),
      resourceIngredient(Resource.BONE, 15),
      resourceIngredient(Resource.FROST_MIRRIAM, 3),
    ],
    output: productIngredient(Product.WOOD_ELF_BONE_CHIMES),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.EPIC,
    url: "https://eso-housing.com/furniture/wood-elf-bone-chimes",
    key: "design: wood elf bone chimes",
  },
  "design: wood elf pitcher, painted": {
    name: "Design: Wood Elf Pitcher, Painted",
    categoryKey: Category.HEARTH,
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.DECORATIVE_WAX, 7),
      resourceIngredient(Resource.REGULUS, 5),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 5),
      resourceIngredient(Resource.BONE, 10),
      resourceIngredient(Resource.RUBY, 8),
      resourceIngredient(Resource.BERVEZ_JUICE, 3),
    ],
    output: productIngredient(Product.WOOD_ELF_PITCHER_PAINTED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/wood-elf-pitcher-painted",
    key: "design: wood elf pitcher, painted",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Diagram
  "diagram: breton sconce, torch": {
    name: "Diagram: Breton Sconce, Torch",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 5),
      resourceIngredient(Resource.MOLYBDENUM, 5),
      resourceIngredient(Resource.MUNDANE_RUNE, 3),
      resourceIngredient(Resource.HONING_STONE, 9),
    ],
    output: productIngredient(Product.BRETON_SCONCE_TORCH),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/breton-sconce-torch",
    key: "diagram: breton sconce, torch",
  },
  "diagram: dark elf candle, claw base": {
    name: "Diagram: Dark Elf Candle, Claw Base",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 4),
      resourceIngredient(Resource.OBSIDIAN, 5),
      resourceIngredient(Resource.RAKEIPA, 4),
      resourceIngredient(Resource.MUNDANE_RUNE, 3),
      resourceIngredient(Resource.HONING_STONE, 9),
    ],
    output: productIngredient(Product.DARK_ELF_CANDLE_CLAW_BASE),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/dark-elf-candle-claw-base",
    key: "diagram: dark elf candle, claw base",
  },
  "diagram: dark elf cauldron, banded": {
    name: "Diagram: Dark Elf Cauldron, Banded",
    categoryKey: Category.HEARTH,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 9),
      resourceIngredient(Resource.DECORATIVE_WAX, 6),
      resourceIngredient(Resource.OBSIDIAN, 10),
      resourceIngredient(Resource.DWARVEN_OIL, 6),
    ],
    output: productIngredient(Product.DARK_ELF_CAULDRON_BANDED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/dark-elf-cauldron-banded",
    key: "diagram: dark elf cauldron, banded",
  },
  "diagram: nord candleholder, cup": {
    name: "Diagram: Nord Candleholder, Cup",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 7),
      resourceIngredient(Resource.MUNDANE_RUNE, 4),
      resourceIngredient(Resource.DECORATIVE_WAX, 4),
      resourceIngredient(Resource.CORUNDUM, 5),
      resourceIngredient(Resource.HONING_STONE, 9),
    ],
    output: productIngredient(Product.NORD_CANDLEHOLDER_CUP),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/nord-candleholder-cup",
    key: "diagram: nord candleholder, cup",
  },
  "diagram: orcish chandelier, practical": {
    name: "Diagram: Orcish Chandelier, Practical",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 10),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 7),
      resourceIngredient(Resource.DECORATIVE_WAX, 6),
      resourceIngredient(Resource.MANGANESE, 10),
      resourceIngredient(Resource.DWARVEN_OIL, 6),
    ],
    output: productIngredient(Product.ORCISH_CHANDELIER_PRACTICAL),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/orcish-chandelier-practical",
    key: "diagram: orcish chandelier, practical",
  },
  "diagram: orcish lantern, hooded": {
    name: "Diagram: Orcish Lantern, Hooded",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 6),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 4),
      resourceIngredient(Resource.MANGANESE, 5),
      resourceIngredient(Resource.HONING_STONE, 9),
    ],
    output: productIngredient(Product.ORCISH_LANTERN_HOODED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/orcish-lantern-hooded",
    key: "diagram: orcish lantern, hooded",
  },
  "diagram: redguard streetlamp, single": {
    name: "Diagram: Redguard Streetlamp, Single",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.BLACKSMITHING,
    inputs: [
      resourceIngredient(Resource.REGULUS, 7),
      resourceIngredient(Resource.HEARTWOOD, 5),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.HONING_STONE, 9),
    ],
    output: productIngredient(Product.REDGUARD_STREETLAMP_SINGLE),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-streetlamp-single",
    key: "diagram: redguard streetlamp, single",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Formula
  "formula: dark elf lantern, oil": {
    name: "Formula: Dark Elf Lantern, Oil",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ALCHEMY,
    inputs: [
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 5),
      resourceIngredient(Resource.OBSIDIAN, 5),
      resourceIngredient(Resource.RAKEIPA, 6),
      resourceIngredient(Resource.MUNDANE_RUNE, 3),
    ],
    output: productIngredient(Product.DARK_ELF_LANTERN_OIL),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/dark-elf-lantern-oil",
    key: "formula: dark elf lantern, oil",
  },
  "formula: dres lantern, stationary": {
    name: "Formula: Dres Lantern, Stationary",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ALCHEMY,
    inputs: [
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 6),
      resourceIngredient(Resource.REGULUS, 3),
      resourceIngredient(Resource.OBSIDIAN, 8),
    ],
    output: productIngredient(Product.DRES_LANTERN_STATIONARY),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/dres-lantern-stationary",
    key: "formula: dres lantern, stationary",
  },
  "formula: indoril streetlight, full stone": {
    name: "Formula: Indoril Streetlight, Full Stone",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ALCHEMY,
    inputs: [
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 6),
      resourceIngredient(Resource.MUNDANE_RUNE, 4),
      resourceIngredient(Resource.OBSIDIAN, 8),
    ],
    output: productIngredient(Product.INDORIL_STREETLIGHT_FULL_STONE),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/indoril-streetlight-full-stone",
    key: "formula: indoril streetlight, full stone",
  },
  "formula: indoril streetlight, stone": {
    name: "Formula: Indoril Streetlight, Stone",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ALCHEMY,
    inputs: [
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 6),
      resourceIngredient(Resource.MUNDANE_RUNE, 3),
      resourceIngredient(Resource.OBSIDIAN, 8),
    ],
    output: productIngredient(Product.INDORIL_STREETLIGHT_STONE),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/indoril-streetlight-stone",
    key: "formula: indoril streetlight, stone",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Pattern
  "pattern: khajiit carpet, crescent moons": {
    name: "Pattern: Khajiit Carpet, Crescent Moons",
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 6),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 3),
      resourceIngredient(Resource.MOONSTONE, 5),
      resourceIngredient(Resource.HEMMING, 9),
    ],
    output: productIngredient(Product.KHAJIIT_CARPET_CRESCENT_MOONS),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/khajiit-carpet-crescent-moons",
    key: "pattern: khajiit carpet, crescent moons",
  },
  "pattern: orcish banner, worn": {
    name: "Pattern: Orcish Banner, Worn",
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.CLEAN_PELT, 6),
      resourceIngredient(Resource.HEARTWOOD, 4),
      resourceIngredient(Resource.MANGANESE, 5),
      resourceIngredient(Resource.HEMMING, 9),
    ],
    output: productIngredient(Product.ORCISH_BANNER_WORN),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/orcish-banner-worn",
    key: "pattern: orcish banner, worn",
  },
  "pattern: redguard armchair, cushioned": {
    name: "Pattern: Redguard Armchair, Cushioned",
    categoryKey: Category.DINING,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 10),
      resourceIngredient(Resource.HEARTWOOD, 7),
      resourceIngredient(Resource.STARMETAL, 10),
      resourceIngredient(Resource.EMBROIDERY, 6),
    ],
    output: productIngredient(Product.REDGUARD_ARMCHAIR_CUSHIONED),
    qualityKey: Quality.SUPERIOR,
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=14172&ItemNamePattern=Pattern:+Redguard+Armchair,+Cushioned&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-armchair-cushioned",
    key: "pattern: redguard armchair, cushioned",
  },
  "pattern: redguard armchair, starry": {
    name: "Pattern: Redguard Armchair, Starry",
    categoryKey: Category.DINING,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 11),
      resourceIngredient(Resource.MUNDANE_RUNE, 6),
      resourceIngredient(Resource.HEARTWOOD, 9),
      resourceIngredient(Resource.STARMETAL, 15),
      resourceIngredient(Resource.ELEGANT_LINING, 3),
    ],
    output: productIngredient(Product.REDGUARD_ARMCHAIR_STARRY),
    qualityKey: Quality.EPIC,
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=14040&ItemNamePattern=Pattern%3A+Redguard+Armchair%2C+Starry&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-armchair-starry",
    key: "pattern: redguard armchair, starry",
  },
  "pattern: redguard bench, padded": {
    name: "Pattern: Redguard Bench, Padded",
    categoryKey: Category.DINING,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 10),
      resourceIngredient(Resource.REGULUS, 6),
      resourceIngredient(Resource.HEARTWOOD, 8),
      resourceIngredient(Resource.STARMETAL, 15),
      resourceIngredient(Resource.RUBY, 12),
      resourceIngredient(Resource.ELEGANT_LINING, 3),
    ],
    output: productIngredient(Product.REDGUARD_BENCH_PADDED),
    qualityKey: Quality.EPIC,
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=13900&ItemNamePattern=Pattern%3A+Redguard+Bench%2C+Padded&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-bench-padded",
    key: "pattern: redguard bench, padded",
  },
  "pattern: redguard carpet, dunes": {
    name: "Pattern: Redguard Carpet, Dunes",
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 10),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 6),
      resourceIngredient(Resource.STARMETAL, 10),
      resourceIngredient(Resource.RUBY, 14),
      resourceIngredient(Resource.EMBROIDERY, 6),
    ],
    output: productIngredient(Product.REDGUARD_CARPET_DUNES),
    qualityKey: Quality.SUPERIOR,
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=14301&ItemNamePattern=Pattern%3A+Redguard+Carpet%2C+Dunes&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-carpet-dunes",
    key: "pattern: redguard carpet, dunes",
  },
  "pattern: redguard curtain, smoky": {
    name: "Pattern: Redguard Curtain, Smoky",
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 5),
      resourceIngredient(Resource.STARMETAL, 5),
      resourceIngredient(Resource.RUBY, 6),
      resourceIngredient(Resource.HEMMING, 9),
    ],
    output: productIngredient(Product.REDGUARD_CURTAIN_SMOKY),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/redguard-curtain-smoky",
    key: "pattern: redguard curtain, smoky",
  },
  "pattern: redguard mat, sunset": {
    name: "Pattern: Redguard Mat, Sunset",
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 9),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 5),
      resourceIngredient(Resource.STARMETAL, 10),
      resourceIngredient(Resource.RUBY, 12),
      resourceIngredient(Resource.EMBROIDERY, 6),
    ],
    output: productIngredient(Product.REDGUARD_MAT_SUNSET),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/redguard-mat-sunset",
    key: "pattern: redguard mat, sunset",
  },
  "pattern: redguard runner, sun": {
    name: "Pattern: Redguard Runner, Sun",
    qualityKey: Quality.SUPERIOR,
    categoryKey: Category.PARLOR,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.BAST, 10),
      resourceIngredient(Resource.ALCHEMICAL_RESIN, 5),
      resourceIngredient(Resource.DECORATIVE_WAX, 5),
      resourceIngredient(Resource.STARMETAL, 10),
      resourceIngredient(Resource.EMBROIDERY, 6),
    ],
    output: productIngredient(Product.REDGUARD_RUNNER_SUN),
    ttcUrl:
      "https://us.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=12073&ItemNamePattern=Pattern%3A+Redguard+Runner%2C+Sun&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax=&SortBy=Price&Order=asc",
    url: "https://eso-housing.com/furniture/redguard-runner-sun",
    key: "pattern: redguard runner, sun",
  },
  "pattern: wood elf divider, relaxed": {
    name: "Pattern: Wood Elf Divider, Relaxed",
    categoryKey: Category.SUITE,
    craftKey: Craft.CLOTHING,
    inputs: [
      resourceIngredient(Resource.CLEAN_PELT, 10),
      resourceIngredient(Resource.DECORATIVE_WAX, 6),
      resourceIngredient(Resource.HEARTWOOD, 7),
      resourceIngredient(Resource.BONE, 10),
      resourceIngredient(Resource.EMBROIDERY, 6),
    ],
    output: productIngredient(Product.WOOD_ELF_DIVIDER_RELAXED),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/wood-elf-divider-relaxed",
    key: "pattern: wood elf divider, relaxed",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Praxis
  "praxis: breton amphora, ceramic": {
    name: "Praxis: Breton Amphora, Ceramic",
    categoryKey: Category.HEARTH,
    craftKey: Craft.ENCHANTING,
    inputs: [
      resourceIngredient(Resource.MUNDANE_RUNE, 6),
      resourceIngredient(Resource.REGULUS, 4),
      resourceIngredient(Resource.MOLYBDENUM, 5),
      resourceIngredient(Resource.JEJOTA, 9),
    ],
    output: productIngredient(Product.BRETON_AMPHORA_CERAMIC),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/breton-amphora-ceramic",
    key: "praxis: breton amphora, ceramic",
  },
  "praxis: hagraven cauldron, ritual": {
    name: "Praxis: Hagraven Cauldron, Ritual",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ENCHANTING,
    inputs: [
      resourceIngredient(Resource.MUNDANE_RUNE, 9),
      resourceIngredient(Resource.BAST, 5),
      resourceIngredient(Resource.DECORATIVE_WAX, 4),
      resourceIngredient(Resource.BRONZE, 12),
      resourceIngredient(Resource.DENATA, 6),
    ],
    output: productIngredient(Product.HAGRAVEN_CAULDRON_RITUAL),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://eso-housing.com/furniture/hagraven-cauldron-ritual",
    key: "praxis: hagraven cauldron, ritual",
  },
  "praxis: orcish brazier, smoldering": {
    name: "Praxis: Orcish Brazier, Smoldering",
    categoryKey: Category.LIGHTING,
    craftKey: Craft.ENCHANTING,
    inputs: [
      resourceIngredient(Resource.MUNDANE_RUNE, 5),
      resourceIngredient(Resource.HEARTWOOD, 3),
      resourceIngredient(Resource.MANGANESE, 5),
      resourceIngredient(Resource.RAKEIPA, 6),
      resourceIngredient(Resource.JEJOTA, 9),
    ],
    output: productIngredient(Product.ORCISH_BRAZIER_SMOLDERING),
    ownerKey: Character.FRAK_LOCK,
    qualityKey: Quality.FINE,
    url: "https://eso-housing.com/furniture/orcish-brazier-smoldering",
    key: "praxis: orcish brazier, smoldering",
  },
  // ///////////////////////////////////////////////////////////////////////////
  // Recipe
  "recipe: lava foot soup-and-saltrice": {
    name: "Recipe: Lava Foot Soup-and-Saltrice",
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.SALTRICE),
      resourceIngredient(Resource.FLOUR),
      resourceIngredient(Resource.POTATO),
      resourceIngredient(Resource.SCRIB_JELLY),
    ],
    output: productIngredient(Product.LAVA_FOOT_SOUP_AND_SALTRICE),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.SUPERIOR,
    url: "https://www.esofinder.com/en/recipes/96967",
    key: "recipe: lava foot soup-and-saltrice",
  },
  "recipe: witchmother's potent brew": {
    name: "Recipe: Witchmother's Potent Brew",
    craftKey: Craft.PROVISIONING,
    inputs: [
      resourceIngredient(Resource.NIGHTSHADE),
      resourceIngredient(Resource.BERVEZ_JUICE),
      resourceIngredient(Resource.RICE),
      resourceIngredient(Resource.SMALL_GAME),
    ],
    output: productIngredient(Product.WITCHMOTHERS_POTENT_BREW),
    ownerKey: Character.KALED_LOCK,
    qualityKey: Quality.EPIC,
    url:
      "http://teso-guides.com/the-elder-scrolls-online-special-recipes-witchmothers-potent-brew",
    key: "recipe: witchmother's potent brew",
  },
};

Recipe.keys = () => Object.keys(Recipe.properties);

Recipe.values = () => Object.values(Recipe.properties);

Object.freeze(Recipe);

export default Recipe;
